-- ============================================================================
-- K-MAT IA - MODELO RELACIONAL MEJORADO PARA DIAGRAMAR
--
-- Dialecto: Oracle SQL / Oracle SQL Developer Data Modeler.
-- Para Supabase/PostgreSQL convertir VARCHAR2(36) a UUID, NUMBER a NUMERIC
-- cuando corresponda, CHAR(1) S/N a BOOLEAN y TIMESTAMP a TIMESTAMPTZ.
--
-- Este archivo NO reemplaza bd_kmatia.sql; es una versión ampliada para el
-- diagrama relacional y la futura implementación del MVP.
-- ============================================================================

-- 1. Adultos autenticados: docentes y responsables.
CREATE TABLE USUARIO (
    ID_USUARIO             VARCHAR2(36)  NOT NULL,
    AUTH_USER_ID           VARCHAR2(36)  NOT NULL,
    NOMBRE                 VARCHAR2(100) NOT NULL,
    CORREO                 VARCHAR2(150) NOT NULL,
    ROL                    VARCHAR2(20)  NOT NULL,
    ESTADO                 CHAR(1)       DEFAULT 'A' NOT NULL,
    FECHA_CREACION         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_ELIMINACION      TIMESTAMP,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_USUARIO_AUTH UNIQUE (AUTH_USER_ID),
    CONSTRAINT UQ_USUARIO_CORREO UNIQUE (CORREO),
    CONSTRAINT CK_USUARIO_ROL CHECK (ROL IN ('DOCENTE', 'RESPONSABLE')),
    CONSTRAINT CK_USUARIO_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

-- 2. Secuencia pedagógica interna.
CREATE TABLE NIVEL_APRENDIZAJE (
    ID_NIVEL               VARCHAR2(36)  NOT NULL,
    NOMBRE_NIVEL           VARCHAR2(100) NOT NULL,
    DESCRIPCION            VARCHAR2(500),
    ORDEN_NIVEL            NUMBER        NOT NULL,
    ESTADO                 CHAR(1)       DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_NIVEL_APRENDIZAJE PRIMARY KEY (ID_NIVEL),
    CONSTRAINT UQ_NIVEL_ORDEN UNIQUE (ORDEN_NIVEL),
    CONSTRAINT CK_NIVEL_ORDEN CHECK (ORDEN_NIVEL > 0),
    CONSTRAINT CK_NIVEL_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

-- 3. Perfil infantil. No requiere cuenta ni contraseña propia.
CREATE TABLE ESTUDIANTE (
    ID_ESTUDIANTE          VARCHAR2(36)  NOT NULL,
    ID_RESPONSABLE         VARCHAR2(36)  NOT NULL,
    ID_NIVEL_ACTUAL        VARCHAR2(36),
    NOMBRE                 VARCHAR2(100) NOT NULL,
    AVATAR                 VARCHAR2(255),
    NIVEL_EDUCATIVO        VARCHAR2(20)  NOT NULL,
    ESTADO                 CHAR(1)       DEFAULT 'A' NOT NULL,
    FECHA_CREACION         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_ELIMINACION      TIMESTAMP,
    CONSTRAINT PK_ESTUDIANTE PRIMARY KEY (ID_ESTUDIANTE),
    CONSTRAINT FK_ESTUDIANTE_RESPONSABLE
        FOREIGN KEY (ID_RESPONSABLE) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_ESTUDIANTE_NIVEL
        FOREIGN KEY (ID_NIVEL_ACTUAL) REFERENCES NIVEL_APRENDIZAJE(ID_NIVEL),
    CONSTRAINT CK_ESTUDIANTE_NIVEL_EDU CHECK (NIVEL_EDUCATIVO IN ('NT1', 'NT2')),
    CONSTRAINT CK_ESTUDIANTE_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

-- 4. Consentimiento y su trazabilidad. Un estudiante puede tener varias
-- versiones históricas del documento, pero solo una vigente por propósito.
CREATE TABLE CONSENTIMIENTO (
    ID_CONSENTIMIENTO      VARCHAR2(36) NOT NULL,
    ID_ESTUDIANTE          VARCHAR2(36) NOT NULL,
    ID_RESPONSABLE         VARCHAR2(36) NOT NULL,
    VERSION_DOCUMENTO      VARCHAR2(30) NOT NULL,
    PROPOSITO              VARCHAR2(30) NOT NULL,
    ESTADO                 VARCHAR2(20) NOT NULL,
    FECHA_OTORGAMIENTO     TIMESTAMP,
    FECHA_REVOCACION       TIMESTAMP,
    FECHA_CREACION         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_CONSENTIMIENTO PRIMARY KEY (ID_CONSENTIMIENTO),
    CONSTRAINT FK_CONSENT_ESTUDIANTE
        FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
    CONSTRAINT FK_CONSENT_RESPONSABLE
        FOREIGN KEY (ID_RESPONSABLE) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT CK_CONSENT_PROPOSITO CHECK (PROPOSITO IN ('USO_PLATAFORMA', 'ANALITICA', 'RECURSOS_EXTERNOS')),
    CONSTRAINT CK_CONSENT_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'OTORGADO', 'REVOCADO')),
    CONSTRAINT CK_CONSENT_FECHAS CHECK (
        FECHA_REVOCACION IS NULL OR FECHA_OTORGAMIENTO IS NULL
        OR FECHA_REVOCACION >= FECHA_OTORGAMIENTO
    )
);

-- 5. Sala de seguimiento creada por un docente.
CREATE TABLE GRUPO (
    ID_GRUPO               VARCHAR2(36)  NOT NULL,
    ID_DOCENTE             VARCHAR2(36)  NOT NULL,
    NOMBRE_GRUPO           VARCHAR2(100) NOT NULL,
    CODIGO_UNION           VARCHAR2(20)  NOT NULL,
    ESTADO                 CHAR(1)       DEFAULT 'A' NOT NULL,
    FECHA_CREACION         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_GRUPO PRIMARY KEY (ID_GRUPO),
    CONSTRAINT UQ_GRUPO_CODIGO UNIQUE (CODIGO_UNION),
    CONSTRAINT FK_GRUPO_DOCENTE FOREIGN KEY (ID_DOCENTE) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT CK_GRUPO_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

-- 6. Relación histórica N:M entre estudiante y grupo.
CREATE TABLE INSCRIPCION_GRUPO (
    ID_INSCRIPCION         VARCHAR2(36) NOT NULL,
    ID_GRUPO               VARCHAR2(36) NOT NULL,
    ID_ESTUDIANTE          VARCHAR2(36) NOT NULL,
    ESTADO                 VARCHAR2(20) DEFAULT 'ACTIVA' NOT NULL,
    FECHA_INICIO           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_FIN              TIMESTAMP,
    CONSTRAINT PK_INSCRIPCION_GRUPO PRIMARY KEY (ID_INSCRIPCION),
    CONSTRAINT FK_INSC_GRUPO FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO(ID_GRUPO),
    CONSTRAINT FK_INSC_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
    CONSTRAINT UQ_INSC_GRUPO_ESTUDIANTE UNIQUE (ID_GRUPO, ID_ESTUDIANTE, FECHA_INICIO),
    CONSTRAINT CK_INSC_ESTADO CHECK (ESTADO IN ('ACTIVA', 'FINALIZADA', 'RETIRADA')),
    CONSTRAINT CK_INSC_FECHAS CHECK (FECHA_FIN IS NULL OR FECHA_FIN >= FECHA_INICIO)
);

-- 7. Habilidad o contenido matemático del currículo MVP.
CREATE TABLE CONTENIDO (
    ID_CONTENIDO           VARCHAR2(36)  NOT NULL,
    NOMBRE_CONTENIDO       VARCHAR2(100) NOT NULL,
    DESCRIPCION            VARCHAR2(500),
    NIVEL_EDUCATIVO        VARCHAR2(20)  NOT NULL,
    ORDEN_CONTENIDO        NUMBER        NOT NULL,
    ESTADO                 CHAR(1)       DEFAULT 'A' NOT NULL,
    CONSTRAINT PK_CONTENIDO PRIMARY KEY (ID_CONTENIDO),
    CONSTRAINT UQ_CONTENIDO_ORDEN UNIQUE (NIVEL_EDUCATIVO, ORDEN_CONTENIDO),
    CONSTRAINT CK_CONTENIDO_NIVEL_EDU CHECK (NIVEL_EDUCATIVO IN ('NT1', 'NT2')),
    CONSTRAINT CK_CONTENIDO_ORDEN CHECK (ORDEN_CONTENIDO > 0),
    CONSTRAINT CK_CONTENIDO_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

-- 8. Banco de ejercicios. La versión evita reinterpretar el historial al editar
-- un ejercicio. CONFIGURACION almacena alternativas u orden esperado en JSON
-- al migrar a PostgreSQL (JSONB).
CREATE TABLE EJERCICIO (
    ID_EJERCICIO           VARCHAR2(36)   NOT NULL,
    ID_CONTENIDO           VARCHAR2(36)   NOT NULL,
    ID_NIVEL               VARCHAR2(36)   NOT NULL,
    VERSION                NUMBER         DEFAULT 1 NOT NULL,
    TIPO_EJERCICIO         VARCHAR2(30)   NOT NULL,
    TIPO_RESPUESTA         VARCHAR2(30)   NOT NULL,
    ENUNCIADO              VARCHAR2(1000) NOT NULL,
    RESPUESTA_CORRECTA     VARCHAR2(1000),
    CONFIGURACION          CLOB,
    DIFICULTAD             NUMBER         NOT NULL,
    RECURSO_URI            VARCHAR2(500),
    DISPONIBLE_OFFLINE     CHAR(1)        DEFAULT 'S' NOT NULL,
    ESTADO                 CHAR(1)        DEFAULT 'A' NOT NULL,
    FECHA_PUBLICACION      TIMESTAMP,
    FECHA_ACTUALIZACION    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_ELIMINACION      TIMESTAMP,
    CONSTRAINT PK_EJERCICIO PRIMARY KEY (ID_EJERCICIO),
    CONSTRAINT FK_EJERCICIO_CONTENIDO FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID_CONTENIDO),
    CONSTRAINT FK_EJERCICIO_NIVEL FOREIGN KEY (ID_NIVEL) REFERENCES NIVEL_APRENDIZAJE(ID_NIVEL),
    CONSTRAINT CK_EJERCICIO_VERSION CHECK (VERSION > 0),
    CONSTRAINT CK_EJERCICIO_TIPO CHECK (TIPO_EJERCICIO IN ('CONTEO', 'SECUENCIA', 'CONTEO_SALTOS', 'COMPARACION', 'CLASIFICACION', 'PATRON', 'SUMA', 'RESTA', 'PROBLEMA', 'ORDENAR')),
    CONSTRAINT CK_EJERCICIO_RESPUESTA CHECK (TIPO_RESPUESTA IN ('MANUSCRITA', 'SELECCION', 'ORDENAMIENTO')),
    CONSTRAINT CK_EJERCICIO_DIFICULTAD CHECK (DIFICULTAD BETWEEN 1 AND 5),
    CONSTRAINT CK_EJERCICIO_OFFLINE CHECK (DISPONIBLE_OFFLINE IN ('S', 'N')),
    CONSTRAINT CK_EJERCICIO_ESTADO CHECK (ESTADO IN ('BORRADOR', 'A', 'I'))
);

-- 9. Catálogo de pistas, pausas activas, videos y material de apoyo.
CREATE TABLE RECURSO_APOYO (
    ID_RECURSO             VARCHAR2(36)   NOT NULL,
    ID_CONTENIDO           VARCHAR2(36),
    TIPO_RECURSO           VARCHAR2(30)   NOT NULL,
    TITULO                 VARCHAR2(150)  NOT NULL,
    DESCRIPCION            VARCHAR2(1000),
    RECURSO_URI            VARCHAR2(500),
    ETAPA_APOYO            NUMBER         DEFAULT 1 NOT NULL,
    DURACION_SEGUNDOS      NUMBER,
    DISPONIBLE_OFFLINE     CHAR(1)        DEFAULT 'S' NOT NULL,
    ESTADO                 CHAR(1)        DEFAULT 'A' NOT NULL,
    FECHA_ACTUALIZACION    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_RECURSO_APOYO PRIMARY KEY (ID_RECURSO),
    CONSTRAINT FK_RECURSO_CONTENIDO FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID_CONTENIDO),
    CONSTRAINT CK_RECURSO_TIPO CHECK (TIPO_RECURSO IN ('PAUSA_ACTIVA', 'PISTA', 'ACTIVIDAD_ALTERNATIVA', 'JUEGO', 'VIDEO', 'MATERIAL_APOYO')),
    CONSTRAINT CK_RECURSO_ETAPA CHECK (ETAPA_APOYO BETWEEN 1 AND 5),
    CONSTRAINT CK_RECURSO_DURACION CHECK (DURACION_SEGUNDOS IS NULL OR DURACION_SEGUNDOS >= 0),
    CONSTRAINT CK_RECURSO_OFFLINE CHECK (DISPONIBLE_OFFLINE IN ('S', 'N')),
    CONSTRAINT CK_RECURSO_ESTADO CHECK (ESTADO IN ('A', 'I'))
);

-- 10. Periodo de trabajo de un estudiante.
CREATE TABLE SESION_APRENDIZAJE (
    ID_SESION              VARCHAR2(36) NOT NULL,
    ID_ESTUDIANTE          VARCHAR2(36) NOT NULL,
    TIPO_SESION            VARCHAR2(20) NOT NULL,
    FECHA_INICIO           TIMESTAMP    NOT NULL,
    FECHA_FIN              TIMESTAMP,
    ESTADO                 VARCHAR2(20) NOT NULL,
    FECHA_ACTUALIZACION    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_SESION_APRENDIZAJE PRIMARY KEY (ID_SESION),
    CONSTRAINT FK_SESION_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
    CONSTRAINT CK_SESION_TIPO CHECK (TIPO_SESION IN ('DIAGNOSTICO', 'PRACTICA', 'REFUERZO')),
    CONSTRAINT CK_SESION_ESTADO CHECK (ESTADO IN ('EN_CURSO', 'COMPLETADA', 'INTERRUMPIDA')),
    CONSTRAINT CK_SESION_FECHAS CHECK (FECHA_FIN IS NULL OR FECHA_FIN >= FECHA_INICIO)
);

-- 11. Solicitud del docente para reforzar un contenido.
CREATE TABLE REFUERZO_DOCENTE (
    ID_REFUERZO            VARCHAR2(36) NOT NULL,
    ID_DOCENTE             VARCHAR2(36) NOT NULL,
    ID_ESTUDIANTE          VARCHAR2(36) NOT NULL,
    ID_CONTENIDO           VARCHAR2(36) NOT NULL,
    ID_RECURSO             VARCHAR2(36),
    TIPO_REFUERZO          VARCHAR2(30) NOT NULL,
    CANTIDAD_EJERCICIOS    NUMBER,
    ESTADO                 VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    OBSERVACION            VARCHAR2(500),
    FECHA_ASIGNACION       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_COMPLETADO       TIMESTAMP,
    FECHA_ACTUALIZACION    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_REFUERZO_DOCENTE PRIMARY KEY (ID_REFUERZO),
    CONSTRAINT FK_REFUERZO_DOCENTE FOREIGN KEY (ID_DOCENTE) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_REFUERZO_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
    CONSTRAINT FK_REFUERZO_CONTENIDO FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID_CONTENIDO),
    CONSTRAINT FK_REFUERZO_RECURSO FOREIGN KEY (ID_RECURSO) REFERENCES RECURSO_APOYO(ID_RECURSO),
    CONSTRAINT CK_REFUERZO_TIPO CHECK (TIPO_REFUERZO IN ('MAS_EJERCICIOS', 'ACTIVIDAD_ALTERNATIVA', 'JUEGO', 'VIDEO', 'MATERIAL_APOYO')),
    CONSTRAINT CK_REFUERZO_CANTIDAD CHECK (CANTIDAD_EJERCICIOS IS NULL OR CANTIDAD_EJERCICIOS > 0),
    CONSTRAINT CK_REFUERZO_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'ACTIVO', 'COMPLETADO', 'CANCELADO')),
    CONSTRAINT CK_REFUERZO_FECHAS CHECK (FECHA_COMPLETADO IS NULL OR FECHA_COMPLETADO >= FECHA_ASIGNACION)
);

-- 12. Ejercicio entregado a un estudiante. VERSION_EJERCICIO conserva el
-- contexto evaluado aun cuando después se modifique el banco de ejercicios.
CREATE TABLE ASIGNACION_EJERCICIO (
    ID_ASIGNACION          VARCHAR2(36) NOT NULL,
    ID_ESTUDIANTE          VARCHAR2(36) NOT NULL,
    ID_EJERCICIO           VARCHAR2(36) NOT NULL,
    ID_SESION              VARCHAR2(36),
    ID_REFUERZO            VARCHAR2(36),
    VERSION_EJERCICIO      NUMBER       NOT NULL,
    ORIGEN_ASIGNACION      VARCHAR2(20) NOT NULL,
    PRIORIDAD              NUMBER       DEFAULT 1 NOT NULL,
    ORDEN_COLA             NUMBER,
    ESTADO                 VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    FECHA_ASIGNACION       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_INICIO           TIMESTAMP,
    FECHA_COMPLETADO       TIMESTAMP,
    FECHA_ACTUALIZACION    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_ASIGNACION_EJERCICIO PRIMARY KEY (ID_ASIGNACION),
    CONSTRAINT FK_ASIG_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
    CONSTRAINT FK_ASIG_EJERCICIO FOREIGN KEY (ID_EJERCICIO) REFERENCES EJERCICIO(ID_EJERCICIO),
    CONSTRAINT FK_ASIG_SESION FOREIGN KEY (ID_SESION) REFERENCES SESION_APRENDIZAJE(ID_SESION),
    CONSTRAINT FK_ASIG_REFUERZO FOREIGN KEY (ID_REFUERZO) REFERENCES REFUERZO_DOCENTE(ID_REFUERZO),
    CONSTRAINT CK_ASIG_VERSION CHECK (VERSION_EJERCICIO > 0),
    CONSTRAINT CK_ASIG_ORIGEN CHECK (ORIGEN_ASIGNACION IN ('DIAGNOSTICO', 'MOTOR', 'DOCENTE')),
    CONSTRAINT CK_ASIG_PRIORIDAD CHECK (PRIORIDAD > 0),
    CONSTRAINT CK_ASIG_ORDEN CHECK (ORDEN_COLA IS NULL OR ORDEN_COLA > 0),
    CONSTRAINT CK_ASIG_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'EN_CURSO', 'COMPLETADA', 'CANCELADA')),
    CONSTRAINT CK_ASIG_FECHAS CHECK ((FECHA_INICIO IS NULL OR FECHA_INICIO >= FECHA_ASIGNACION) AND (FECHA_COMPLETADO IS NULL OR FECHA_COMPLETADO >= FECHA_ASIGNACION))
);

-- 13. Cada intento preserva lo reconocido por ML Kit y lo finalmente confirmado.
CREATE TABLE INTENTO_EJERCICIO (
    ID_INTENTO             VARCHAR2(36)  NOT NULL,
    ID_ASIGNACION          VARCHAR2(36)  NOT NULL,
    RESPUESTA_RECONOCIDA   VARCHAR2(1000),
    RESPUESTA_FINAL        VARCHAR2(1000),
    CONFIANZA_RECONOCIMIENTO NUMBER(5,4),
    REQUIRIO_CONFIRMACION  CHAR(1)       DEFAULT 'N' NOT NULL,
    ES_CORRECTA            CHAR(1),
    NUMERO_INTENTO         NUMBER        NOT NULL,
    TIEMPO_RESPUESTA_MS    NUMBER,
    FECHA_HORA             TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_ACTUALIZACION    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_INTENTO_EJERCICIO PRIMARY KEY (ID_INTENTO),
    CONSTRAINT FK_INTENTO_ASIGNACION FOREIGN KEY (ID_ASIGNACION) REFERENCES ASIGNACION_EJERCICIO(ID_ASIGNACION),
    CONSTRAINT UQ_INTENTO_ORDEN UNIQUE (ID_ASIGNACION, NUMERO_INTENTO),
    CONSTRAINT CK_INTENTO_CONFIANZA CHECK (CONFIANZA_RECONOCIMIENTO IS NULL OR CONFIANZA_RECONOCIMIENTO BETWEEN 0 AND 1),
    CONSTRAINT CK_INTENTO_CONFIRMACION CHECK (REQUIRIO_CONFIRMACION IN ('S', 'N')),
    CONSTRAINT CK_INTENTO_CORRECTA CHECK (ES_CORRECTA IS NULL OR ES_CORRECTA IN ('S', 'N')),
    CONSTRAINT CK_INTENTO_NUMERO CHECK (NUMERO_INTENTO > 0),
    CONSTRAINT CK_INTENTO_TIEMPO CHECK (TIEMPO_RESPUESTA_MS IS NULL OR TIEMPO_RESPUESTA_MS >= 0)
);

-- 14. Estado actual por contenido. El historial se calcula desde los intentos.
CREATE TABLE PROGRESO_CONTENIDO (
    ID_ESTUDIANTE          VARCHAR2(36) NOT NULL,
    ID_CONTENIDO           VARCHAR2(36) NOT NULL,
    NIVEL_DOMINIO          VARCHAR2(20) NOT NULL,
    FECHA_ACTUALIZACION    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VERSION_REGISTRO       NUMBER       DEFAULT 1 NOT NULL,
    CONSTRAINT PK_PROGRESO_CONTENIDO PRIMARY KEY (ID_ESTUDIANTE, ID_CONTENIDO),
    CONSTRAINT FK_PROGRESO_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
    CONSTRAINT FK_PROGRESO_CONTENIDO FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO(ID_CONTENIDO),
    CONSTRAINT CK_PROGRESO_DOMINIO CHECK (NIVEL_DOMINIO IN ('NO_INICIADO', 'INICIAL', 'EN_PROCESO', 'DOMINADO')),
    CONSTRAINT CK_PROGRESO_VERSION CHECK (VERSION_REGISTRO > 0)
);

-- 15. Señal pedagógica; no representa un diagnóstico clínico.
CREATE TABLE DETECCION_DIFICULTAD (
    ID_DETECCION           VARCHAR2(36)  NOT NULL,
    ID_ASIGNACION          VARCHAR2(36)  NOT NULL,
    TIPO_DETECCION         VARCHAR2(30)  NOT NULL,
    ERRORES_CONSECUTIVOS   NUMBER,
    INTENTOS_RECIENTES     NUMBER,
    TIEMPO_PROMEDIO_MS     NUMBER,
    NIVEL_SEVERIDAD        VARCHAR2(10)  NOT NULL,
    ESTADO                 VARCHAR2(20)  DEFAULT 'ABIERTA' NOT NULL,
    MOTIVO                 VARCHAR2(500),
    FECHA_HORA             TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_RESOLUCION       TIMESTAMP,
    CONSTRAINT PK_DETECCION_DIFICULTAD PRIMARY KEY (ID_DETECCION),
    CONSTRAINT FK_DETECCION_ASIGNACION FOREIGN KEY (ID_ASIGNACION) REFERENCES ASIGNACION_EJERCICIO(ID_ASIGNACION),
    CONSTRAINT CK_DETECCION_TIPO CHECK (TIPO_DETECCION IN ('TIEMPO_ELEVADO', 'ERRORES_CONSECUTIVOS', 'MULTIPLES_INTENTOS', 'DESEMPENO_RECIENTE', 'COMBINADA')),
    CONSTRAINT CK_DETECCION_ERRORES CHECK (ERRORES_CONSECUTIVOS IS NULL OR ERRORES_CONSECUTIVOS >= 0),
    CONSTRAINT CK_DETECCION_INTENTOS CHECK (INTENTOS_RECIENTES IS NULL OR INTENTOS_RECIENTES >= 0),
    CONSTRAINT CK_DETECCION_TIEMPO CHECK (TIEMPO_PROMEDIO_MS IS NULL OR TIEMPO_PROMEDIO_MS >= 0),
    CONSTRAINT CK_DETECCION_SEVERIDAD CHECK (NIVEL_SEVERIDAD IN ('BAJA', 'MEDIA', 'ALTA')),
    CONSTRAINT CK_DETECCION_ESTADO CHECK (ESTADO IN ('ABIERTA', 'RESUELTA')),
    CONSTRAINT CK_DETECCION_RESOLUCION CHECK (FECHA_RESOLUCION IS NULL OR FECHA_RESOLUCION >= FECHA_HORA)
);

-- 16. Registra el apoyo que realmente recibió el estudiante y su resultado.
CREATE TABLE INTERVENCION_APOYO (
    ID_INTERVENCION        VARCHAR2(36) NOT NULL,
    ID_ESTUDIANTE          VARCHAR2(36) NOT NULL,
    ID_DETECCION           VARCHAR2(36),
    ID_INTENTO             VARCHAR2(36),
    ID_RECURSO             VARCHAR2(36) NOT NULL,
    ORIGEN                 VARCHAR2(20) NOT NULL,
    RESULTADO              VARCHAR2(20) DEFAULT 'MOSTRADO' NOT NULL,
    FECHA_HORA             TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    OBSERVACION            VARCHAR2(500),
    CONSTRAINT PK_INTERVENCION_APOYO PRIMARY KEY (ID_INTERVENCION),
    CONSTRAINT FK_INTERV_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),
    CONSTRAINT FK_INTERV_DETECCION FOREIGN KEY (ID_DETECCION) REFERENCES DETECCION_DIFICULTAD(ID_DETECCION),
    CONSTRAINT FK_INTERV_INTENTO FOREIGN KEY (ID_INTENTO) REFERENCES INTENTO_EJERCICIO(ID_INTENTO),
    CONSTRAINT FK_INTERV_RECURSO FOREIGN KEY (ID_RECURSO) REFERENCES RECURSO_APOYO(ID_RECURSO),
    CONSTRAINT CK_INTERV_ORIGEN CHECK (ORIGEN IN ('MOTOR', 'DOCENTE', 'ESTUDIANTE')),
    CONSTRAINT CK_INTERV_RESULTADO CHECK (RESULTADO IN ('MOSTRADO', 'COMPLETADO', 'OMITIDO', 'ABANDONADO')),
    CONSTRAINT CK_INTERV_REFERENCIA CHECK (ID_DETECCION IS NOT NULL OR ID_INTENTO IS NOT NULL)
);

-- 17. Bitácora de acciones administrativas relevantes. No registra respuestas
-- ni trazos; esos ya viven en las tablas pedagógicas.
CREATE TABLE AUDITORIA (
    ID_AUDITORIA           VARCHAR2(36)   NOT NULL,
    ID_USUARIO             VARCHAR2(36),
    ENTIDAD                VARCHAR2(50)   NOT NULL,
    ID_ENTIDAD             VARCHAR2(36)   NOT NULL,
    ACCION                 VARCHAR2(30)   NOT NULL,
    DETALLE                VARCHAR2(1000),
    FECHA_HORA             TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_AUDITORIA PRIMARY KEY (ID_AUDITORIA),
    CONSTRAINT FK_AUDITORIA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT CK_AUDITORIA_ACCION CHECK (ACCION IN ('CREAR', 'ACTUALIZAR', 'DESACTIVAR', 'REVOCAR_CONSENTIMIENTO', 'ASIGNAR_REFUERZO', 'CAMBIAR_GRUPO'))
);

-- Índices principales para el MVP.
CREATE INDEX IDX_ESTUDIANTE_RESPONSABLE ON ESTUDIANTE(ID_RESPONSABLE);
CREATE INDEX IDX_INSC_ESTUDIANTE ON INSCRIPCION_GRUPO(ID_ESTUDIANTE, ESTADO);
CREATE INDEX IDX_EJERCICIO_BUSQUEDA ON EJERCICIO(ID_CONTENIDO, ID_NIVEL, ESTADO, DIFICULTAD);
CREATE INDEX IDX_SESION_ESTUDIANTE ON SESION_APRENDIZAJE(ID_ESTUDIANTE, FECHA_INICIO);
CREATE INDEX IDX_REFUERZO_ESTUDIANTE ON REFUERZO_DOCENTE(ID_ESTUDIANTE, ESTADO, FECHA_ASIGNACION);
CREATE INDEX IDX_ASIG_ESTUDIANTE ON ASIGNACION_EJERCICIO(ID_ESTUDIANTE, ESTADO, PRIORIDAD);
CREATE INDEX IDX_INTENTO_ASIGNACION ON INTENTO_EJERCICIO(ID_ASIGNACION, NUMERO_INTENTO);
CREATE INDEX IDX_DETECCION_ASIGNACION ON DETECCION_DIFICULTAD(ID_ASIGNACION, ESTADO, FECHA_HORA);
CREATE INDEX IDX_INTERV_ESTUDIANTE ON INTERVENCION_APOYO(ID_ESTUDIANTE, FECHA_HORA);
CREATE INDEX IDX_AUDITORIA_ENTIDAD ON AUDITORIA(ENTIDAD, ID_ENTIDAD, FECHA_HORA);

-- Relaciones principales para el diagrama:
-- USUARIO 1:N ESTUDIANTE (responsable)
-- USUARIO 1:N GRUPO (docente)
-- GRUPO N:M ESTUDIANTE mediante INSCRIPCION_GRUPO
-- ESTUDIANTE 1:N CONSENTIMIENTO, SESION_APRENDIZAJE, REFUERZO_DOCENTE,
--     ASIGNACION_EJERCICIO, PROGRESO_CONTENIDO e INTERVENCION_APOYO
-- CONTENIDO 1:N EJERCICIO, RECURSO_APOYO, REFUERZO_DOCENTE y PROGRESO_CONTENIDO
-- EJERCICIO 1:N ASIGNACION_EJERCICIO
-- ASIGNACION_EJERCICIO 1:N INTENTO_EJERCICIO y DETECCION_DIFICULTAD
-- DETECCION_DIFICULTAD / INTENTO_EJERCICIO -> INTERVENCION_APOYO
--
-- Reglas que deben implementarse con RLS, funciones o lógica de aplicación:
-- 1) ID_DOCENTE debe pertenecer a un USUARIO con ROL = 'DOCENTE'.
-- 2) El responsable del consentimiento debe ser el responsable del estudiante.
-- 3) Una sesión, refuerzo o intervención debe corresponder al mismo estudiante.
-- 4) El docente debe tener un grupo activo que incluya al estudiante intervenido.
-- 5) Para Supabase: enlazar USUARIO.AUTH_USER_ID con auth.users(id), activar
--    RLS y conceder acceso solo a responsable, docente autorizado y backend.
